version: "3.9"  # Update to the latest supported version (currently 3.9)

networks:
  ds-wordpress-net:  # Use a more generic network name
    driver: bridge

services:
  mysql:
    image: mysql:8.0  # Use a more recent and secure MySQL version
    container_name: ds-wordpress-mysql
    restart: unless-stopped  # Restart container automatically on crashes
    volumes:
      - mysql-data:/var/lib/mysql  # Use a named volume for persistence
    environment:
      MYSQL_ROOT_PASSWORD: "your_strong_password"  # Use a strong password, avoid numbers only
      MYSQL_DATABASE: wordpress
      MYSQL_USER: marvin
      MYSQL_PASSWORD: "your_strong_password"
    networks:
      - ds-wordpress-net

  server:
    image: wordpress:latest
    container_name: ds-wordpress
    ports:
      - "80:80"  # Map to standard port 80 for easier access
    volumes:
      - wordpress-data:/var/www/html  # Use a named volume for persistence
    environment:
      WORDPRESS_DB_USER: marvin
      WORDPRESS_DB_PASSWORD: "marvin"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql  # Simplified hostname within the network
    depends_on:
      - mysql
    networks:
      - ds-wordpress-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ds-phpmyadmin
    ports:
      - "8080:80"  # Map to standard port 8080 for easier access
    environment:
      PMA_HOST: mysql  # Simplified hostname within the network
      MYSQL_ROOT_PASSWORD: "your_strong_password"
    depends_on:
      - mysql
    networks:
      - ds-wordpress-net

# Define volumes for persistence (outside the service definitions)
volumes:
  mysql-data: {}
  wordpress-data: {}
